import os
from supabase import create_client, Client
from app.config import SUPABASE_KEY, SUPABASE_URL

# Initialize the supabase client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)


def add_demo_pieces_to_wardrobe(user_id):
    """
    1. Get the clothes from storage. We;ll probably get it as a list. 
    2. For each clothing item (based of clothing items table),
       a. id - autogenerated by db
       b. we attach this user's id(idk how we'll get that. but it vshould come from the frontend),
       c. give it a name (but how?) 
        Option 1: I can have a dictionary here in the backend so we can match it to the piece from backend
        Option 2: just name the piece in storage what we want it to appear as on gthe user's screen 
       d. Category (4 categories)
        Only thing i can think of is using a dictionary / or if else statement 
       e. fash_category we leave empty 
       f. image_url - gotten from db. 
       i created_at timestamp automatically generated. 
    3. add this to clothing items table. Helpful considerations: claude and I can discuss - pydantic models? 
    """
    storage_response = (
        supabase.storage
        .from_("Clothing Pieces")
        .list("Abrima-default-pieces")
    )

    for clothing_piece in storage_response:
        name = clothing_piece["name"]
        if name == "Black Baggy Jeans" or name == "Khaki Slacks":
            category = "bottoms"
        elif name == "White Tank Top" or name == "Black Fitted Long Sleeve":
            category = "tops"
        else:
            category = "other"
        print(f"name is {name} and category is {category}")
        # get image url
        img_url_storage_response = (
            supabase.storage
            .from_("Clothing Pieces")
            .get_public_url(f"Abrima-default-pieces/{name}")
        )

        # insert data into  clothing items table
        db_response = (
            supabase.table("clothing_items")
            .insert({
                "user_id": user_id,
                "name": name,
                "category": category,
                "image_url": img_url_storage_response[0:]
            })
            .execute()
        )

    return db_response

# user_id="1c54d0c9-8762-423e-a2eb-818973cf54fb"
# print(automatically_upload_pieces_to_wardrobe_on_signup(user_id))
